-- MySQL Script generated by MySQL Workbench
-- vie 13 nov 2020 18:52:23 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONA` (
  `nombre` VARCHAR(45) NOT NULL,
  `area` DECIMAL NULL,
  `concejal` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CALLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CALLE` (
  `nombre` VARCHAR(45) NOT NULL,
  `longitud` DECIMAL NULL,
  `tipo` VARCHAR(45) NULL,
  `cantidad_carriles` INT NULL,
  `zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `zona_idx` (`zona` ASC) VISIBLE,
  CONSTRAINT `zona`
    FOREIGN KEY (`zona`)
    REFERENCES `mydb`.`ZONA` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CONSTRUCCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CONSTRUCCION` (
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `superficie` DECIMAL NULL,
  `año_construccion` INT NULL,
  PRIMARY KEY (`calle`, `numero`),
  CONSTRAINT `calle`
    FOREIGN KEY (`calle`)
    REFERENCES `mydb`.`CALLE` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BLOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BLOQUE` (
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `superficie` DECIMAL NULL,
  PRIMARY KEY (`calle`, `numero`),
  CONSTRAINT `numero`
    FOREIGN KEY (`numero`)
    REFERENCES `mydb`.`CONSTRUCCION` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `calle`
    FOREIGN KEY (`calle`)
    REFERENCES `mydb`.`CONSTRUCCION` (`calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PISO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PISO` (
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `planta` INT NOT NULL,
  `letra` VARCHAR(45) NOT NULL,
  `numero_habitantes` INT NULL,
  `superficie` DECIMAL NULL,
  `dueño` VARCHAR(45) NOT NULL,
  INDEX `dueño_idx` (`dueño` ASC) VISIBLE,
  INDEX `numero_idx` (`numero` ASC) VISIBLE,
  PRIMARY KEY (`calle`, `numero`, `planta`, `letra`),
  CONSTRAINT `numero`
    FOREIGN KEY (`numero`)
    REFERENCES `mydb`.`BLOQUE` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `calle`
    FOREIGN KEY (`calle`)
    REFERENCES `mydb`.`BLOQUE` (`calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dueño`
    FOREIGN KEY (`dueño`)
    REFERENCES `mydb`.`PERSONA` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONA` (
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_nacimiento` VARCHAR(45) NULL,
  `nivel_estudios` VARCHAR(45) NULL,
  `cabeza_familia` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `planta` INT NULL,
  `letra` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`),
  INDEX `cabeza_idx` (`cabeza_familia` ASC) VISIBLE,
  INDEX `direccion_idx` (`calle` ASC, `numero` ASC, `planta` ASC, `letra` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  CONSTRAINT `cabeza_familia`
    FOREIGN KEY (`cabeza_familia`)
    REFERENCES `mydb`.`PERSONA` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `direccion_piso`
    FOREIGN KEY (`calle` , `numero` , `planta` , `letra`)
    REFERENCES `mydb`.`PISO` (`calle` , `numero` , `planta` , `letra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `direccion_unifamiliar`
    FOREIGN KEY (`calle` , `numero`)
    REFERENCES `mydb`.`UNIFAMILIAR` (`calle` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UNIFAMILIAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UNIFAMILIAR` (
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `numero_habitantes` INT NULL,
  `superficie` DECIMAL NULL,
  `dueño` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`calle`, `numero`),
  INDEX `dueño_idx` (`dueño` ASC) VISIBLE,
  CONSTRAINT `numero`
    FOREIGN KEY (`numero`)
    REFERENCES `mydb`.`CONSTRUCCION` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `calle`
    FOREIGN KEY (`calle`)
    REFERENCES `mydb`.`CONSTRUCCION` (`calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dueño`
    FOREIGN KEY (`dueño`)
    REFERENCES `mydb`.`PERSONA` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
