-- MySQL Script generated by MySQL Workbench
-- Thu Nov 19 14:33:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema catastro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema catastro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `catastro` DEFAULT CHARACTER SET utf8 ;
USE `catastro` ;

-- -----------------------------------------------------
-- Table `catastro`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`ZONA` (
  `nombre` VARCHAR(45) NOT NULL,
  `area` DECIMAL NULL,
  `concejal` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`CALLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`CALLE` (
  `nombre` VARCHAR(45) NOT NULL,
  `longitud` DECIMAL NULL,
  `tipo` VARCHAR(45) NULL,
  `cantidad_carriles` INT NULL,
  `zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_calle_zona_idx` (`zona` ASC),
  CONSTRAINT `fk_calle_zona`
    FOREIGN KEY (`zona`)
    REFERENCES `catastro`.`ZONA` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`CONSTRUCCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`CONSTRUCCION` (
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `superficie` DECIMAL NULL,
  `año_construccion` INT NULL,
  PRIMARY KEY (`calle`, `numero`),
  CONSTRAINT `fk_construccion_calle`
    FOREIGN KEY (`calle`)
    REFERENCES `catastro`.`CALLE` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`BLOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`BLOQUE` (
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `superficie` DECIMAL NULL,
  PRIMARY KEY (`calle`, `numero`),
  CONSTRAINT `fk_bloque_construccion`
    FOREIGN KEY (`calle` , `numero`)
    REFERENCES `catastro`.`CONSTRUCCION` (`calle` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`PISO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`PISO` (
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `planta` INT NOT NULL,
  `letra` VARCHAR(45) NOT NULL,
  `numero_habitantes` INT NULL,
  `superficie` DECIMAL NULL,
  `dueño` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`calle`, `numero`, `planta`, `letra`),
  INDEX `fk_piso_persona_idx` (`dueño` ASC),
  CONSTRAINT `fk_piso_bloque`
    FOREIGN KEY (`calle` , `numero`)
    REFERENCES `catastro`.`BLOQUE` (`calle` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_piso_persona`
    FOREIGN KEY (`dueño`)
    REFERENCES `catastro`.`PERSONA` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`PERSONA` (
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_nacimiento` VARCHAR(45) NULL,
  `nivel_estudios` VARCHAR(45) NULL,
  `cabeza_familia` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `planta` INT NULL,
  `letra` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`),
  INDEX `fk_persona_persona_idx` (`cabeza_familia` ASC),
  INDEX `fk_persona_piso_idx` (`calle` ASC, `numero` ASC, `planta` ASC, `letra` ASC),
  CONSTRAINT `fk_persona_persona`
    FOREIGN KEY (`cabeza_familia`)
    REFERENCES `catastro`.`PERSONA` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_piso`
    FOREIGN KEY (`calle` , `numero` , `planta` , `letra`)
    REFERENCES `catastro`.`PISO` (`calle` , `numero` , `planta` , `letra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`UNIFAMILIAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`UNIFAMILIAR` (
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `numero_habitantes` INT NULL,
  `superficie` DECIMAL NULL,
  `dueño` VARCHAR(45) NOT NULL,
  INDEX `fk_unifamiliar_persona_idx` (`dueño` ASC),
  PRIMARY KEY (`calle`, `numero`),
  CONSTRAINT `fk_unifamiliar_persona`
    FOREIGN KEY (`dueño`)
    REFERENCES `catastro`.`PERSONA` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unifamiliar_construccion`
    FOREIGN KEY (`calle` , `numero`)
    REFERENCES `catastro`.`CONSTRUCCION` (`calle` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
