-- MySQL Script generated by MySQL Workbench
-- vie 13 nov 2020 20:07:05 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`VIVERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VIVERO` (
  `nombre` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  `hora_apertura` VARCHAR(45) NULL,
  `hora_cierre` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre`, `ubicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZONAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONAS` (
  `nombre` VARCHAR(45) NOT NULL,
  `VIVERO_nombre` VARCHAR(45) NOT NULL,
  `VIVERO_ubicacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`, `VIVERO_nombre`, `VIVERO_ubicacion`),
  INDEX `fk_ZONAS_VIVERO_idx` (`VIVERO_nombre` ASC, `VIVERO_ubicacion` ASC) VISIBLE,
  CONSTRAINT `fk_ZONAS_VIVERO`
    FOREIGN KEY (`VIVERO_nombre` , `VIVERO_ubicacion`)
    REFERENCES `mydb`.`VIVERO` (`nombre` , `ubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO` (
  `codigo_barras` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `stock` INT NULL,
  `tipo` VARCHAR(45) NULL,
  `caducidad` DATETIME NULL,
  `precio` DECIMAL NULL,
  PRIMARY KEY (`codigo_barras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO` (
  `dni` VARCHAR(45) NOT NULL,
  `css` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `tipo_contrato` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`, `css`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `codigo_fidelizacion` INT NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `numero_tarjeta` VARCHAR(45) NULL,
  `bonificacion` DECIMAL NULL,
  `gasto_mensual` DECIMAL NULL,
  PRIMARY KEY (`codigo_fidelizacion`, `dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO` (
  `codigo_pedido` INT NOT NULL,
  `fecha` DATETIME NULL,
  `precio` DECIMAL NULL,
  `EMPLEADO_dni` VARCHAR(45) NOT NULL,
  `EMPLEADO_css` VARCHAR(45) NOT NULL,
  `CLIENTE_codigo_fidelizacion` INT NOT NULL,
  `CLIENTE_dni` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_pedido`),
  INDEX `fk_PEDIDO_EMPLEADO1_idx` (`EMPLEADO_dni` ASC, `EMPLEADO_css` ASC) VISIBLE,
  INDEX `fk_PEDIDO_CLIENTE1_idx` (`CLIENTE_codigo_fidelizacion` ASC, `CLIENTE_dni` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_dni` , `EMPLEADO_css`)
    REFERENCES `mydb`.`EMPLEADO` (`dni` , `css`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_codigo_fidelizacion` , `CLIENTE_dni`)
    REFERENCES `mydb`.`CLIENTE` (`codigo_fidelizacion` , `dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZONAS_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONAS_PRODUCTO` (
  `ZONAS_nombre` VARCHAR(45) NOT NULL,
  `ZONAS_VIVERO_nombre` VARCHAR(45) NOT NULL,
  `ZONAS_VIVERO_ubicacion` VARCHAR(45) NOT NULL,
  `PRODUCTO_codigo_barras` VARCHAR(45) NOT NULL,
  `stock` INT NULL,
  PRIMARY KEY (`ZONAS_nombre`, `ZONAS_VIVERO_nombre`, `ZONAS_VIVERO_ubicacion`, `PRODUCTO_codigo_barras`),
  INDEX `fk_ZONAS_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_codigo_barras` ASC) VISIBLE,
  INDEX `fk_ZONAS_has_PRODUCTO_ZONAS1_idx` (`ZONAS_nombre` ASC, `ZONAS_VIVERO_nombre` ASC, `ZONAS_VIVERO_ubicacion` ASC) VISIBLE,
  CONSTRAINT `fk_ZONAS_has_PRODUCTO_ZONAS1`
    FOREIGN KEY (`ZONAS_nombre` , `ZONAS_VIVERO_nombre` , `ZONAS_VIVERO_ubicacion`)
    REFERENCES `mydb`.`ZONAS` (`nombre` , `VIVERO_nombre` , `VIVERO_ubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZONAS_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_codigo_barras`)
    REFERENCES `mydb`.`PRODUCTO` (`codigo_barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZONAS_EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONAS_EMPLEADO` (
  `ZONAS_nombre` VARCHAR(45) NOT NULL,
  `ZONAS_VIVERO_nombre` VARCHAR(45) NOT NULL,
  `ZONAS_VIVERO_ubicacion` VARCHAR(45) NOT NULL,
  `EMPLEADO_dni` VARCHAR(45) NOT NULL,
  `EMPLEADO_css` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATETIME NULL,
  `fehca_fin` DATETIME NULL,
  PRIMARY KEY (`ZONAS_nombre`, `ZONAS_VIVERO_nombre`, `ZONAS_VIVERO_ubicacion`, `EMPLEADO_dni`, `EMPLEADO_css`),
  INDEX `fk_ZONAS_has_EMPLEADO_EMPLEADO1_idx` (`EMPLEADO_dni` ASC, `EMPLEADO_css` ASC) VISIBLE,
  INDEX `fk_ZONAS_has_EMPLEADO_ZONAS1_idx` (`ZONAS_nombre` ASC, `ZONAS_VIVERO_nombre` ASC, `ZONAS_VIVERO_ubicacion` ASC) VISIBLE,
  CONSTRAINT `fk_ZONAS_has_EMPLEADO_ZONAS1`
    FOREIGN KEY (`ZONAS_nombre` , `ZONAS_VIVERO_nombre` , `ZONAS_VIVERO_ubicacion`)
    REFERENCES `mydb`.`ZONAS` (`nombre` , `VIVERO_nombre` , `VIVERO_ubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZONAS_has_EMPLEADO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_dni` , `EMPLEADO_css`)
    REFERENCES `mydb`.`EMPLEADO` (`dni` , `css`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO_PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO_PEDIDO` (
  `PRODUCTO_codigo_barras` VARCHAR(45) NOT NULL,
  `PEDIDO_codigo_pedido` INT NOT NULL,
  PRIMARY KEY (`PRODUCTO_codigo_barras`, `PEDIDO_codigo_pedido`),
  INDEX `fk_PRODUCTO_has_PEDIDO_PEDIDO1_idx` (`PEDIDO_codigo_pedido` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_has_PEDIDO_PRODUCTO1_idx` (`PRODUCTO_codigo_barras` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_has_PEDIDO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_codigo_barras`)
    REFERENCES `mydb`.`PRODUCTO` (`codigo_barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_has_PEDIDO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_codigo_pedido`)
    REFERENCES `mydb`.`PEDIDO` (`codigo_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
