-- MySQL Script generated by MySQL Workbench
-- Thu Nov 19 14:18:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vivero
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vivero
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vivero` DEFAULT CHARACTER SET utf8 ;
USE `vivero` ;

-- -----------------------------------------------------
-- Table `vivero`.`VIVERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`VIVERO` (
  `nombre` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  `hora_apertura` VARCHAR(45) NULL,
  `hora_cierre` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre`, `ubicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`ZONAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`ZONAS` (
  `nombre` VARCHAR(45) NOT NULL,
  `vivero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`, `vivero`),
  INDEX `fk_zonas_vivero_idx` (`vivero` ASC),
  CONSTRAINT `fk_zonas_vivero`
    FOREIGN KEY (`vivero`)
    REFERENCES `vivero`.`VIVERO` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`PRODUCTO` (
  `codigo_barras` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `stock` INT NULL,
  `tipo` VARCHAR(45) NULL,
  `caducidad` DATETIME NULL,
  `precio` DECIMAL NULL,
  PRIMARY KEY (`codigo_barras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`EMPLEADO` (
  `dni` VARCHAR(45) NOT NULL,
  `css` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `tipo_contrato` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`),
  UNIQUE INDEX `css_UNIQUE` (`css` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`CLIENTE` (
  `dni` VARCHAR(45) NOT NULL,
  `codigo_fidelizacion` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `numero_tarjeta` VARCHAR(45) NULL,
  `bonificacion` DECIMAL NULL,
  `gasto_mensual` DECIMAL NULL,
  PRIMARY KEY (`dni`),
  UNIQUE INDEX `codigo_fidelizacion_UNIQUE` (`codigo_fidelizacion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`PEDIDO` (
  `codigo_pedido` INT NOT NULL,
  `fecha` DATETIME NULL,
  `precio` DECIMAL NULL,
  `empleado` VARCHAR(45) NOT NULL,
  `cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_pedido`),
  INDEX `fk_pedido_empleado_idx` (`empleado` ASC),
  INDEX `fk_pedido_cliente_idx` (`cliente` ASC),
  CONSTRAINT `fk_pedido_empleado`
    FOREIGN KEY (`empleado`)
    REFERENCES `vivero`.`EMPLEADO` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `vivero`.`CLIENTE` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`ZONAS_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`ZONAS_PRODUCTO` (
  `zona` VARCHAR(45) NOT NULL,
  `vivero` VARCHAR(45) NOT NULL,
  `codigo_barras` VARCHAR(45) NOT NULL,
  `stock` INT NULL,
  PRIMARY KEY (`zona`, `vivero`, `codigo_barras`),
  INDEX `fk_zonas_producto_producto_idx` (`codigo_barras` ASC),
  CONSTRAINT `fk_zonas_producto_zonas`
    FOREIGN KEY (`zona` , `vivero`)
    REFERENCES `vivero`.`ZONAS` (`nombre` , `vivero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zonas_producto_producto`
    FOREIGN KEY (`codigo_barras`)
    REFERENCES `vivero`.`PRODUCTO` (`codigo_barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`PRODUCTO_PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`PRODUCTO_PEDIDO` (
  `codigo_barras` VARCHAR(45) NOT NULL,
  `codigo_pedido` INT NOT NULL,
  PRIMARY KEY (`codigo_barras`, `codigo_pedido`),
  INDEX `fk_producto_pedido_pedido_idx` (`codigo_pedido` ASC),
  CONSTRAINT `fk_producto_pedido_producto`
    FOREIGN KEY (`codigo_barras`)
    REFERENCES `vivero`.`PRODUCTO` (`codigo_barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_pedido_pedido`
    FOREIGN KEY (`codigo_pedido`)
    REFERENCES `vivero`.`PEDIDO` (`codigo_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`ZONAS_EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`ZONAS_EMPLEADO` (
  `zona` VARCHAR(45) NOT NULL,
  `vivero` VARCHAR(45) NOT NULL,
  `empleado` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATETIME NULL,
  `fecha_fin` DATETIME NULL,
  PRIMARY KEY (`zona`, `vivero`, `empleado`),
  INDEX `fk_zonas_empleado_empleado_idx` (`empleado` ASC),
  CONSTRAINT `fk_zonas_empleado_zonas`
    FOREIGN KEY (`zona` , `vivero`)
    REFERENCES `vivero`.`ZONAS` (`nombre` , `vivero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zonas_empleado_empleado`
    FOREIGN KEY (`empleado`)
    REFERENCES `vivero`.`EMPLEADO` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
